const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const srcDir = path.join(rootDir, 'web-src');
const outDir = path.join(rootDir, 'assets', 'papergrapher');
const indexPath = path.join(srcDir, 'index.html');
const outputPath = path.join(outDir, 'index.html');
const moduleOutputPath = path.join(rootDir, 'papergrapherHtml.ts');

function readText(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function readBinary(filePath) {
  return fs.readFileSync(filePath);
}

function toDataUri(filePath, mimeType) {
  const base64 = readBinary(filePath).toString('base64');
  return `data:${mimeType};base64,${base64}`;
}

function safeJson(value) {
  return JSON.stringify(value).replace(/<\/script/gi, '<\\/script');
}

function escapeInlineScript(content) {
  return content.replace(/<\/script/gi, '<\\/script');
}

function escapeForTemplateLiteral(content) {
  return content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

function writeHtmlModule(html) {
  const escaped = escapeForTemplateLiteral(html);
  const moduleContents = [
    '// Auto-generated by scripts/build-inline.js',
    'export const papergrapherHtml = `',
    escaped,
    '`;',
    ''
  ].join('\n');

  fs.writeFileSync(moduleOutputPath, moduleContents, 'utf8');
}

function replaceCssAssets(css, replacements) {
  return replacements.reduce((acc, replacement) => {
    const { pattern, value } = replacement;
    return acc.replace(pattern, `url('${value}')`);
  }, css);
}

function patchToolbarJs(content) {
  const needle = "$tool.css({'background-image': 'url(assets/tools/tool_'+tool.id+'.svg)'});";
  if (!content.includes(needle)) {
    return content;
  }

  const replacement = [
    "var toolIcon = window.__PG_TOOL_ICONS__ && window.__PG_TOOL_ICONS__[tool.id];",
    "var fallbackIcon = window.__PG_TOOL_ICON_FALLBACK__ || null;",
    "if (toolIcon) {",
    "\t$tool.css({'background-image': 'url(' + toolIcon + ')'});",
    "} else if (fallbackIcon) {",
    "\t$tool.css({'background-image': 'url(' + fallbackIcon + ')'});",
    "}"
  ].join('\n\t\t\t');

  return content.replace(needle, replacement);
}

function patchTextJs(content) {
  const getJsonBlock = "\t\tjQuery.getJSON('fonts/fonts.json', function(data){\n\t\t\tjQuery.each(data.fonts, function(index, fontName) {";
  if (content.includes(getJsonBlock)) {
    const replacement = "\t\tvar data = { fonts: (window.__PG_FONT_LIST__ || []) };\n\t\t\tjQuery.each(data.fonts, function(index, fontName) {\n\t\t\t\tvar fontSource = (window.__PG_FONT_DATA__ && window.__PG_FONT_DATA__[fontName]) ? window.__PG_FONT_DATA__[fontName] : 'fonts/' + fontName;";
    content = content.replace(getJsonBlock, replacement);
  }

  const loadNeedle = "opentype.load('fonts/'+fontName, function (err, font) {";
  content = content.replace(loadNeedle, 'opentype.load(fontSource, function (err, font) {');

  content = content.replace("\t\t\t});\n\t\t});", "\t\t\t});");

  return content;
}

function patchCodeEditorJs(content) {
  const cssBlock = [
    '\t\tjQuery("<link />", {',
    '\t\t\thref: "css/codeEditor.css",',
    '\t\t\trel: "stylesheet",',
    '\t\t\tid: "codeEditorCSS"',
    '\t\t}).appendTo("head");'
  ].join('\n');

  if (content.includes(cssBlock)) {
    const replacement = [
      '\t\tif (window.__PG_CODE_EDITOR_CSS__) {',
      '\t\t\tif (!document.getElementById("codeEditorCSS")) {',
      '\t\t\t\tjQuery("<style />", { id: "codeEditorCSS" })',
      '\t\t\t\t\t.text(window.__PG_CODE_EDITOR_CSS__)',
      '\t\t\t\t\t.appendTo("head");',
      '\t\t\t}',
      '\t\t} else {',
      '\t\t\tjQuery("<link />", {',
      '\t\t\t\thref: "css/codeEditor.css",',
      '\t\t\t\trel: "stylesheet",',
      '\t\t\t\tid: "codeEditorCSS"',
      '\t\t\t}).appendTo("head");',
      '\t\t}'
    ].join('\n');
    content = content.replace(cssBlock, replacement);
  }

  const scriptsBlock = [
    "\t\tjQuery.getJSON('user/scripts/scripts.json', function(data) {",
    '\t\t\tjQuery.each(data.scripts, function(index, scriptID) {',
    '\t\t\t\tvar $option = jQuery(\'<option value="\'+scriptID+\'">\'+scriptID+\'.js</option>\');',
    '\t\t\t\t$select.append($option);',
    '\t\t\t});',
    '\t\t});'
  ].join('\n');

  if (content.includes(scriptsBlock)) {
    const replacement = [
      '\t\tvar data = window.__PG_USER_SCRIPTS__ || { scripts: [] };',
      '\t\tjQuery.each((data.scripts || []), function(index, scriptID) {',
      '\t\t\tvar $option = jQuery(\'<option value="\'+scriptID+\'">\'+scriptID+\'.js</option>\');',
      '\t\t\t$select.append($option);',
      '\t\t});'
    ].join('\n');
    content = content.replace(scriptsBlock, replacement);
  }

  const ajaxBlock = [
    '\t\t\tjQuery.ajax({',
    "\t\t\t\turl: 'user/scripts/'+scriptID+'.js',",
    "\t\t\t\tdataType: 'text',",
    '\t\t\t\tsuccess: function(data) {',
    "\t\t\t\t\tjQuery('#codeEditorArea').val(data);",
    '\t\t\t\t}',
    '\t\t\t});'
  ].join('\n');

  if (content.includes(ajaxBlock)) {
    const replacement = [
      '\t\t\tvar scriptsData = window.__PG_USER_SCRIPTS__ && window.__PG_USER_SCRIPTS__.content',
      '\t\t\t\t? window.__PG_USER_SCRIPTS__.content',
      '\t\t\t\t: {};',
      '\t\t\tif (scriptsData && scriptsData[scriptID]) {',
      "\t\t\t\tjQuery('#codeEditorArea').val(scriptsData[scriptID]);",
      '\t\t\t} else {',
      "\t\t\t\tjQuery('#codeEditorArea').val(defaultScript);",
      '\t\t\t}'
    ].join('\n');
    content = content.replace(ajaxBlock, replacement);
  }

  return content;
}

function patchLayerPanelJs(content) {
  const loadStart = content.indexOf('var loadResources = function() {');
  if (loadStart === -1) {
    return content;
  }
  const loadEnd = content.indexOf('};', loadStart);
  if (loadEnd === -1) {
    return content;
  }
  const replacement = [
    'var loadResources = function() {',
    '\tif (window.__PG_LAYER_PANEL_CSS__) {',
    '\t\tif (!document.getElementById("layerPanelCSS")) {',
    '\t\t\tjQuery("<style />", { id: "layerPanelCSS" })',
    '\t\t\t\t.text(window.__PG_LAYER_PANEL_CSS__)',
    '\t\t\t\t.appendTo("head");',
    '\t\t}',
    '\t\treturn;',
    '\t}',
    '\tif(!jQuery(\'#layerPanelCSS\').exists()) {',
    '\t\tjQuery(\"<link />\", {',
    '\t\t\thref: \"css/layerPanel.css\",',
    '\t\t\trel: \"stylesheet\",',
    '\t\t\tid: \"layerPanelCSS\"',
    '\t\t}).appendTo(\"head\", function() {',
    '\t\t\treturn true;',
    '\t\t});',
    '\t};',
    '};'
  ].join('\n');
  return content.slice(0, loadStart) + replacement + content.slice(loadEnd + 2);
}

function patchSettingsJs(content) {
  const replacement = [
    '\t\tvar data = window.__PG_CONFIG__;',
    '\t\tif (!data) {',
    '\t\t\tconsole.error(\'Loading config.json failed: Not Found\');',
    '\t\t\treturn;',
    '\t\t}',
    '\t\tvar storage = window.__PG_STORAGE__;',
    '\t\t',
    '\t\tconfig = data;',
    '\t\tvar storageVersionNumber = storage ? storage.getItem("pg.version") : null;',
    '\t\tif(storageVersionNumber && storageVersionNumber !== config.appVersion) {',
    '\t\t\tconsole.warn(\'Settings version mismatch. Reverting all settings to default for now.\');',
    '\t\t\tclearSettings();',
    '\t\t} else if(!storageVersionNumber) {',
    '\t\t\tsetVersionNumber();',
    '\t\t}',
    '\t\t',
    '\t\tdocument.title = \'Papergrapher \' + config.appVersion;'
  ].join('\n');

  const ajaxStart = content.indexOf('jQuery.ajax({');
  if (ajaxStart === -1) {
    return content;
  }

  const errorStart = content.indexOf('}).error', ajaxStart);
  if (errorStart === -1) {
    return content;
  }

  const ajaxEnd = content.indexOf('});', errorStart);
  if (ajaxEnd === -1) {
    return content;
  }

  var updated = content.slice(0, ajaxStart) + replacement + content.slice(ajaxEnd + 3);
  return updated.replace(/localStorage\./g, 'window.__PG_STORAGE__.');
}

function patchScript(src, content) {
  if (src === 'js/toolbar.js') {
    return patchToolbarJs(content);
  }
  if (src === 'js/text.js') {
    return patchTextJs(content);
  }
  if (src === 'js/settings.js') {
    return patchSettingsJs(content);
  }
  if (src === 'js/codeEditor.js') {
    return patchCodeEditorJs(content);
  }
  if (src === 'js/layerPanel.js') {
    return patchLayerPanelJs(content);
  }
  return content;
}

function buildInlineHtml() {
  if (!fs.existsSync(indexPath)) {
    throw new Error(`Missing source index.html at ${indexPath}`);
  }

  const html = readText(indexPath);
  const cssLinks = [];
  const scriptTags = [];

  let processed = html.replace(/<link[^>]*href="([^"]+)"[^>]*>/g, (match, href) => {
    if (href.startsWith('css/')) {
      cssLinks.push(href);
      return '';
    }
    return match;
  });

  processed = processed.replace(/<script\s+[^>]*src="([^"]+)"[^>]*><\/script>/g, (match, src) => {
    const typeMatch = match.match(/type="([^"]+)"/);
    const dataCanvasMatch = match.match(/data-paper-canvas="([^"]+)"/);
    scriptTags.push({
      src,
      type: typeMatch ? typeMatch[1] : null,
      dataCanvas: dataCanvasMatch ? dataCanvasMatch[1] : null
    });
    return '';
  });

  const toolIcons = {};
  const toolsDir = path.join(srcDir, 'assets', 'tools');
  if (fs.existsSync(toolsDir)) {
    for (const file of fs.readdirSync(toolsDir)) {
      if (!file.startsWith('tool_') || !file.endsWith('.svg')) continue;
      const id = file.slice('tool_'.length, -'.svg'.length);
      toolIcons[id] = toDataUri(path.join(toolsDir, file), 'image/svg+xml');
    }
  }
  const toolFallbackIcon = toolIcons.select || Object.values(toolIcons)[0] || '';

  const fontListPath = path.join(srcDir, 'fonts', 'fonts.json');
  const fontsJson = JSON.parse(readText(fontListPath));
  const fontList = Array.isArray(fontsJson.fonts) ? fontsJson.fonts : [];
  const fontData = {};
  for (const fontName of fontList) {
    const fontPath = path.join(srcDir, 'fonts', fontName);
    if (fs.existsSync(fontPath)) {
      fontData[fontName] = toDataUri(fontPath, 'font/ttf');
    }
  }

  const userScriptsPath = path.join(srcDir, 'user', 'scripts', 'scripts.json');
  const userScriptsJson = JSON.parse(readText(userScriptsPath));
  const userScriptList = Array.isArray(userScriptsJson.scripts) ? userScriptsJson.scripts : [];
  const userScriptContent = {};
  for (const scriptId of userScriptList) {
    const scriptPath = path.join(srcDir, 'user', 'scripts', `${scriptId}.js`);
    if (fs.existsSync(scriptPath)) {
      userScriptContent[scriptId] = readText(scriptPath);
    }
  }

  const codeEditorCss = readText(path.join(srcDir, 'css', 'codeEditor.css'));
  const layerPanelCss = readText(path.join(srcDir, 'css', 'layerPanel.css'));
  const configJson = JSON.parse(readText(path.join(srcDir, 'config.json')));

  const iconSwitchPath = path.join(srcDir, 'assets', 'icon_switchColor.svg');
  const selectButtonPath = path.join(srcDir, 'assets', 'selectButton.png');

  const cssReplacements = [
    {
      pattern: /url\((['"]?)\.\.\/assets\/icon_switchColor\.svg\1\)/g,
      value: toDataUri(iconSwitchPath, 'image/svg+xml')
    },
    {
      pattern: /url\((['"]?)\.\.\/assets\/selectButton\.png\1\)/g,
      value: toDataUri(selectButtonPath, 'image/png')
    }
  ];

  const embedCss = [
    '/* embed overrides */',
    'html, body {',
    '\tbackground-color: #fff;',
    '\tmargin: 0;',
    '\tpadding: 0;',
    '}',
    ':root {',
    '\t--pg-topbar: 30px;',
    '\t--pg-sidebar: 76px;',
    '}',
    '#paperCanvas {',
    '\tbackground-color: #fff !important;',
    '\ttop: var(--pg-topbar) !important;',
    '\tleft: var(--pg-sidebar) !important;',
    '\twidth: calc(100% - var(--pg-sidebar)) !important;',
    '\theight: calc(100% - var(--pg-topbar)) !important;',
    '}',
    '#loadingScreen,',
    '#appNav,',
    '#toolbar,',
    '#statusBar,',
    '#menuInputBlocker,',
    '#colorInputBlocker {',
    '\tdisplay: none !important;',
    '}'
  ].join('\n');

  const cssInline = cssLinks
    .map((href) => {
      const cssPath = path.join(srcDir, href);
      const cssContent = replaceCssAssets(readText(cssPath), cssReplacements);
      return `/* ${href} */\n${cssContent}`;
    })
    .join('\n\n')
    .concat('\n\n', embedCss);

  const initIndex = scriptTags.findIndex((tag) => tag.src === 'js/init.js');
  const extraScripts = ['js/lib/stacktrace.js', 'js/lib/taboverride.min.js'];
  if (initIndex >= 0) {
    const inserts = extraScripts.map((src) => ({ src, type: null, dataCanvas: null }));
    scriptTags.splice(initIndex, 0, ...inserts);
  } else {
    for (const src of extraScripts) {
      scriptTags.push({ src, type: null, dataCanvas: null });
    }
  }

  const storageShimScript = [
    '(function () {',
    '  if (typeof window === "undefined") return;',
    '  var memoryStore = {};',
    '  function createMemoryStorage() {',
    '    return {',
    '      getItem: function (key) {',
    '        return Object.prototype.hasOwnProperty.call(memoryStore, key) ? memoryStore[key] : null;',
    '      },',
    '      setItem: function (key, value) {',
    '        memoryStore[key] = String(value);',
    '      },',
    '      removeItem: function (key) {',
    '        delete memoryStore[key];',
    '      },',
    '      clear: function () {',
    '        memoryStore = {};',
    '      }',
    '    };',
    '  }',
    '  function tryLocalStorage() {',
    '    try {',
    '      if (!("localStorage" in window)) return null;',
    '      var ls = window.localStorage;',
    '      if (!ls) return null;',
    '      var testKey = "__pg_test__";',
    '      ls.setItem(testKey, "1");',
    '      ls.removeItem(testKey);',
    '      return ls;',
    '    } catch (e) {',
    '      return null;',
    '    }',
    '  }',
    '  var storage = null;',
    '  try {',
    '    storage = window.__PG_STORAGE__ || null;',
    '  } catch (e) {}',
    '  if (!storage) {',
    '    storage = tryLocalStorage() || createMemoryStorage();',
    '  }',
    '  window.__PG_STORAGE__ = storage;',
    '})();'
  ].join('\n');

  const bootstrapScript = [
    storageShimScript,
    'window.__PG_TOOL_ICONS__ = ' + safeJson(toolIcons) + ';',
    'window.__PG_TOOL_ICON_FALLBACK__ = ' + safeJson(toolFallbackIcon) + ';',
    'window.__PG_FONT_LIST__ = ' + safeJson(fontList) + ';',
    'window.__PG_FONT_DATA__ = ' + safeJson(fontData) + ';',
    'window.__PG_USER_SCRIPTS__ = ' + safeJson({ scripts: userScriptList, content: userScriptContent }) + ';',
    'window.__PG_CODE_EDITOR_CSS__ = ' + safeJson(codeEditorCss) + ';',
    'window.__PG_LAYER_PANEL_CSS__ = ' + safeJson(layerPanelCss) + ';',
    'window.__PG_CONFIG__ = ' + safeJson(configJson) + ';'
  ].join('\n');

  const canvasHintScript = [
    '(function () {',
    '  try {',
    '    if (typeof HTMLCanvasElement === "undefined") return;',
    '    var originalGetContext = HTMLCanvasElement.prototype.getContext;',
    '    if (!originalGetContext || originalGetContext.__pg_patched) return;',
    '    HTMLCanvasElement.prototype.getContext = function (type, options) {',
    '      if (type === "2d") {',
    '        var nextOptions = options ? Object.assign({}, options, { willReadFrequently: true }) : { willReadFrequently: true };',
    '        return originalGetContext.call(this, type, nextOptions);',
    '      }',
    '      return originalGetContext.call(this, type, options);',
    '    };',
    '    HTMLCanvasElement.prototype.getContext.__pg_patched = true;',
    '  } catch (error) {}',
    '})();'
  ].join('\n');

  const commandBridgeScript = [
    '(function () {',
    '  var queue = [];',
    '  function isReady() {',
    '    return !!(window.pg && pg.toolbar && pg.stylebar && pg.undo && pg.export);',
    '  }',
    '  function applyColor(kind, color) {',
    '    try {',
    '      if (kind === "fill") {',
    '        pg.stylebar.setFillColor(color);',
    '        pg.stylebar.applyFillColorToSelection(color);',
    '      } else {',
    '        pg.stylebar.setStrokeColor(color);',
    '        pg.stylebar.applyStrokeColorToSelection(color);',
    '      }',
    '    } catch (e) {}',
    '  }',
    '  function exec(cmd) {',
    '    if (!cmd || !cmd.action) return;',
    '    try {',
    '      switch (cmd.action) {',
    '        case "tool":',
    '          if (cmd.toolId) { pg.toolbar.switchTool(cmd.toolId, true); }',
    '          break;',
    '        case "fillColor":',
    '          applyColor("fill", cmd.color || null);',
    '          break;',
    '        case "strokeColor":',
    '          applyColor("stroke", cmd.color || null);',
    '          break;',
    '        case "strokeWidth":',
    '          if (cmd.value !== undefined && cmd.value !== null) {',
    '            pg.stylebar.setStrokeWidth(cmd.value, true);',
    '            pg.stylebar.applyStrokeWidthToSelection(cmd.value);',
    '          }',
    '          break;',
    '        case "opacity":',
    '          if (cmd.value !== undefined && cmd.value !== null) {',
    '            pg.stylebar.setOpacity(cmd.value, true);',
    '            pg.stylebar.applyOpacityToSelection(cmd.value);',
    '          }',
    '          break;',
    '        case "blendMode":',
    '          if (cmd.value) {',
    '            pg.stylebar.setBlendMode(cmd.value);',
    '            pg.stylebar.applyBlendModeToSelection(cmd.value);',
    '          }',
    '          break;',
    '        case "switchColors":',
    '          pg.stylebar.switchColors();',
    '          break;',
    '        case "undo":',
    '          pg.undo.undo();',
    '          break;',
    '        case "redo":',
    '          pg.undo.redo();',
    '          break;',
    '        case "exportImage":',
    '          pg.export.exportAndPromptImage();',
    '          break;',
    '        case "exportSvg":',
    '          pg.export.exportAndPromptSVG();',
    '          break;',
    '        case "copy":',
    '          pg.edit.copySelectionToClipboard();',
    '          break;',
    '        case "paste":',
    '          pg.edit.pasteObjectsFromClipboard();',
    '          break;',
    '        case "deleteSelection":',
    '          pg.selection.deleteSelection();',
    '          break;',
    '        case "selectAll":',
    '          pg.selection.selectAllItems();',
    '          break;',
    '        case "deselectAll":',
    '          pg.selection.clearSelection();',
    '          break;',
    '        case "invertSelection":',
    '          pg.selection.invertItemSelection();',
    '          break;',
    '        case "randomSelection":',
    '          pg.selection.selectRandomItems();',
    '          break;',
    '        case "selectAllSegments":',
    '          pg.selection.selectAllSegments();',
    '          break;',
    '        case "invertSegments":',
    '          pg.selection.invertSegmentSelection();',
    '          break;',
    '        case "groupSelection":',
    '          pg.group.groupSelection();',
    '          break;',
    '        case "ungroupSelection":',
    '          pg.group.ungroupSelection();',
    '          break;',
    '        case "moveToActiveLayer":',
    '          pg.layer.addSelectedItemsToActiveLayer();',
    '          break;',
    '        case "bringToFront":',
    '          pg.order.bringSelectionToFront();',
    '          break;',
    '        case "sendToBack":',
    '          pg.order.sendSelectionToBack();',
    '          break;',
    '        case "compoundCreate":',
    '          pg.compoundPath.createFromSelection();',
    '          break;',
    '        case "compoundRelease":',
    '          pg.compoundPath.releaseSelection();',
    '          break;',
    '        case "booleanUnite":',
    '          pg.boolean.booleanUnite();',
    '          break;',
    '        case "booleanIntersect":',
    '          pg.boolean.booleanIntersect();',
    '          break;',
    '        case "booleanSubtract":',
    '          pg.boolean.booleanSubtract();',
    '          break;',
    '        case "booleanExclude":',
    '          pg.boolean.booleanExclude();',
    '          break;',
    '        case "booleanDivide":',
    '          pg.boolean.booleanDivide();',
    '          break;',
    '        case "textToOutlines":',
    '          pg.text.convertSelectionToOutlines();',
    '          break;',
    '        case "newDocument":',
    '          pg.document.clear();',
    '          break;',
    '        case "saveDocument":',
    '          pg.document.saveJSONDocument();',
    '          break;',
    '        case "resetSettings":',
    '          pg.settings.clearSettings();',
    '          break;',
    '        case "toggleLayerPanel":',
    '          if (pg.layerPanel && pg.layerPanel.toggleVisibility) { pg.layerPanel.toggleVisibility(); }',
    '          break;',
    '        case "toggleScriptEditor":',
    '          if (pg.codeEditor && pg.codeEditor.toggleVisibility) { pg.codeEditor.toggleVisibility(); }',
    '          break;',
    '        case "showAbout":',
    '          if (pg.menu && pg.menu.showAboutModal) { pg.menu.showAboutModal(); }',
    '          break;',
    '        case "zoomIn":',
    '          if (pg.view && pg.view.zoomBy) { pg.view.zoomBy(1.25); }',
    '          break;',
    '        case "zoomOut":',
    '          if (pg.view && pg.view.zoomBy) { pg.view.zoomBy(1/1.25); }',
    '          break;',
    '        case "setZoom":',
    '          if (cmd.value !== undefined && cmd.value !== null && window.paper && paper.view) {',
    '            paper.view.zoom = cmd.value;',
    '            if (pg.statusbar && pg.statusbar.update) { pg.statusbar.update(); }',
    '          }',
    '          break;',
    '        case "resetZoom":',
    '          if (pg.view && pg.view.resetZoom) { pg.view.resetZoom(); }',
    '          break;',
    '        case "resetPan":',
    '          if (pg.view && pg.view.resetPan) { pg.view.resetPan(); }',
    '          break;',
    '        case "openJson":',
    '          var jsonInput = document.getElementById("fileUploadJSON");',
    '          if (jsonInput) { jsonInput.click(); }',
    '          break;',
    '        case "importImage":',
    '          var imageInput = document.getElementById("fileUploadImage");',
    '          if (imageInput) { imageInput.click(); }',
    '          break;',
    '        case "importSvg":',
    '          var svgInput = document.getElementById("fileUploadSVG");',
    '          if (svgInput) { svgInput.click(); }',
    '          break;',
    '        case "importImageUrl":',
    '          var imgUrl = prompt("Paste URL to Image (jpg, png, gif)", "http://");',
    '          if (imgUrl) { pg.import.importAndAddExternalImage(imgUrl); }',
    '          break;',
    '        case "importSvgUrl":',
    '          var svgUrl = prompt("Paste URL to SVG", "http://");',
    '          if (svgUrl) { pg.import.importAndAddSVG(svgUrl); }',
    '          break;',
    '        case "importImageData":',
    '          if (cmd.dataUrl) { pg.import.importAndAddImage(cmd.dataUrl); }',
    '          break;',
    '        case "importSvgString":',
    '          if (cmd.svgString) { pg.import.importAndAddSVG(cmd.svgString); }',
    '          break;',
    '        case "importJsonString":',
    '          if (cmd.jsonString) { pg.document.loadJSONDocument(cmd.jsonString); }',
    '          break;',
    '        case "resetView":',
    '          if (pg.view && pg.view.resetZoom) { pg.view.resetZoom(); }',
    '          if (pg.view && pg.view.resetPan) { pg.view.resetPan(); }',
    '          break;',
    '      }',
    '    } catch (e) {',
    '      console.warn("Command failed", e);',
    '    }',
    '  }',
    '  function handle(raw) {',
    '    var data = raw;',
    '    if (typeof data === "string") {',
    '      try { data = JSON.parse(data); } catch (e) { data = null; }',
    '    }',
    '    if (!data || data.type !== "pg:command") return;',
    '    if (!isReady()) {',
    '      queue.push(data);',
    '      return;',
    '    }',
    '    exec(data);',
    '  }',
    '  if (window.addEventListener) {',
    '    window.addEventListener("message", function (e) { handle(e.data); });',
    '  }',
    '  if (document && document.addEventListener) {',
    '    document.addEventListener("message", function (e) { handle(e.data); });',
    '  }',
    '  var interval = setInterval(function () {',
    '    if (!isReady()) return;',
    '    while (queue.length) {',
    '      exec(queue.shift());',
    '    }',
    '    clearInterval(interval);',
    '  }, 300);',
    '})();'
  ].join('\n');

  const inlineScripts = [
    `<script>\n${escapeInlineScript(bootstrapScript)}\n</script>`,
    `<script>\n${escapeInlineScript(canvasHintScript)}\n</script>`,
    `<script>\n${escapeInlineScript(commandBridgeScript)}\n</script>`,
    ...scriptTags.map((tag) => {
      const scriptPath = path.join(srcDir, tag.src);
      const raw = readText(scriptPath);
      const patched = escapeInlineScript(patchScript(tag.src, raw));
      const attrs = [];
      if (tag.type) attrs.push(`type="${tag.type}"`);
      if (tag.dataCanvas) attrs.push(`data-paper-canvas="${tag.dataCanvas}"`);
      const attrString = attrs.length ? ' ' + attrs.join(' ') : '';
      return `<script${attrString}>\n${patched}\n</script>`;
    })
  ].join('\n');

  processed = processed.replace(/<\/head>/i, `<style>\n${cssInline}\n</style>\n</head>`);
  processed = processed.replace(/<\/body>/i, `${inlineScripts}\n</body>`);

  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(outputPath, processed, 'utf8');
  writeHtmlModule(processed);

  return outputPath;
}

try {
  const output = buildInlineHtml();
  console.log(`Generated inline HTML at ${output}`);
} catch (error) {
  console.error(error);
  process.exit(1);
}
